version: '3.8'
services:
 nest-app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "3000:3000"
   environment:
     POSTGRES_HOST: 10.0.0.5
     POSTGRES_PORT: 5432
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: nest_crud
   depends_on:
     - db
 db:
   image: postgres
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: nest_crud
