volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: nest_crud
    healthcheck:
      test: pg_isready
    volumes:
      - postgres:/data/nest_crud
    ports:
      - 5432:5432
    restart: on-failure